# Generated by Django 5.0.7 on 2024-07-17 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scan',
            name='end_time',
            field=models.DateTimeField(null=True),
        ),
    ]
